---
hosts: all
become: true
tasks:
  - name: install apache and php packages
    tags: apache,httpd,php
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

  - name: start and enable apache service
    tags: apache,httpd
    service:
      name: apache2
      state: started
      enabled: yes
    notify:
        - Restart apache
   
  - name: restart apache
  service:
    name: apache2
    state: restarted
